### PR TITLE
added gallery view and side-nav

### PR DESCRIPTION
**Pull request by KyleRessLiere**
Dashboard

Added gallery view. Has a generate Card function to generate cards based on users resources. Add collapsible side bar that collapses on hover.

### CODE REVIEW

**Review by sbrad93 — APPROVED** [review]

**Review by briangormanly — CHANGES_REQUESTED** [review]
This is a really good start, the dashboard looks very clean.
Thank you for sending the PR in a small chunk, just like I asked for.

The only reason I am not going to approve it outright for master is even though the existing dashboard does not have a lot of functionality, it does allow creation of goals and resources. Since this would take that away I would prefer if we temporarily added a separate menu item for the new dashboard (while leaving the old in place) until this version allows access to goals / topics and resources and at least as much the functionality as it is replacing.

An alternative would be to continue working off this branch and anyone that wants to use the new dashboard can pull it into their branch. (Although this means that none of those branches can go into master either until it is ready, so option 1 will likely be better long term).

**Review by briangormanly — COMMENTED** [review]
I just noticed that the old dashboard was at the bottom.  This might be okay it looks like the front end team has a meeting tomorrow will talk then if you are on.

**Review by briangormanly — CHANGES_REQUESTED** [review]
This branch is still under development / changing.
Resubmit a PR when the active development calms down enough to get it into main.

**Comment by briangormanly** [comment]
Closing for now... branch is no longer the same as when the RP was opened and is in active development.
Open a new PR when it is ready for main.

**Pull request closed without merging**
