### PR TITLE
ESLint Integration

### PR DESCRIPTION
**Pull request by kiikoh**
I wanted to get this up early this week for people to have a chance to look at this as this will have an effect on how code is written going forward.

### CODE REVIEW

**Comment by kiikoh** [comment]
As you can see there are currently errors in the projects formatting, and github actions was able to spot them for us. 

At the moment there are
```
11954 problems (11761 errors, 193 warnings)
11574 errors and 0 warnings potentially fixable with the `--fix` option.
```

That means there are 380 problems (187 errors, 193 warnings) that are unfixable

<details>
<summary>Errors Found By Rule</summary>

no-undef (total: 103)
no-unused-vars (total: 193)
brace-style (total: 2)
no-useless-escape (total: 14)
no-inner-declarations (total: 16)
no-redeclare (total: 2)
no-case-declarations (total: 36)
no-const-assign (total: 2)
no-empty (total: 10)
no-prototype-builtins (total: 2)

</details>

**Review by briangormanly — COMMENTED** [review]
I really like what this adds, especially from a style perspective. 

Question / thought though, Since using the --fix option will update many lines of code across the whole application, we will need to be vigilant to preform this at a time when there are not a lot of outstanding branches as it is very likely to cause conflicts with changes underway. Thoughts?

**Comment by kiikoh** [comment]
@briangormanly That is a good question, the simplest solution would be to run this over the weekend. Make an announcement ahead of time and in class the following monday that the code will have a bunch of merge conflicts if they don't pull first when they try to develop again. I think most people try to make their pull request on that sunday and probably won't touch it until after that class anyway. 

That will although have a burden on you to go through the pull requests pretty quickly so we can get everything synced up in that window

**Comment by briangormanly** [comment]
I added some scripts to the package.json so lint can be easily used from the command line if desired.
I also pulled the latest changes from main into the branch.

I want to double check the process that all the other devs will take when this branch is pulled to main.

1. npm i <- will install eslint as a devDependency 
2. Install the ESLint plugin for VS code, or appropriate plugin for the IDE they are using. Screen Shot 2022-10-20 at 8 39 57 PM
3. Pay attention to the errors in the UI
4. Run either 'npm run lint-full', 'npm run lint-client', or 'npm run lint-server' before submitting a PR?

Thoughts?
I ran 'npm run lint-full' on the branch (not committed) and it went from 12097 problems down to 404. I am about to check if everything still runs okay.

**Comment by kiikoh** [comment]
Yep, for devs to get the real time linting they will need to have both eslint installed and an extension set up in their editor. A useful feature I use is to set up "format on save" in vscode settings. This will auto format the file you when you press save on it.  

As far as the scripts you set up, they are nice to have but I don't think they will be the primary way of interacting with eslint.

Even if a dev chooses to not do any of these options by the time they submit a PR the linting bot will have responded with changes. And can optionally be enabled to commit to the branch of the PR with the necessary changes.

**Review by cmarcusdimarco — APPROVED** [review]
As I discussed with @briangormanly yesterday morning, I agree that the best time for this to take place is likely the day or two after the Milestone 2 deadline for the reason @kiikoh mentions; most people will probably have submitted their pull requests by then and be inactive for a short period after.

Submitting my approval now so we can be ready to merge to main at that time.

**Review by briangormanly — APPROVED** [review]
Yep. I did it.
Seems to work
All but 8 errors resolved and I created a ticket for those and sent it to the front end team.

**Pull request merged**
