### PR TITLE
Updating ids in dashboard

### PR DESCRIPTION
**Pull request by MaxEnglish**
-Preliminary action for implementing fetch
-added characters to ids to indicate whether they are goals or topics
-no new functionality
-just modifying existing elements to accommodate changes

### CODE REVIEW

**Review by KyleRessLiere — APPROVED** [review]
Looks good everything for our next steps

**Review by briangormanly — APPROVED** [review]
good to go.

**Comment by briangormanly** [comment]
Before this can be merged there are conflicts that must be resolved, I took a quick look but at least some of them require someone with knowledge on the css to make a educated decision. Please pull main into this branch / resolve and push back up! Ready to go once complete.

**Comment by KyleRessLiere** [comment]
Yeah no problem richie said he gonna look into it. I just stopped because I wasnt the reviewer and wanted to make sure it didnt fall onto main

**Pull request merged**
