### PR TITLE
Made changes to footer, signin, signup and about pages.

### PR DESCRIPTION
**Pull request by Murali2255**
Made changes to footer, signin, signup and about pages. Please check and accept PR.

### CODE REVIEW

**Comment by cmarcusdimarco** [comment]
@AntL552 I removed you from this, but you were originally requested on this PR as a reviewer. Just want to make you aware.

**Review by BabithaVakiti — DISMISSED** [review]
Everything looks good.

**Review by Deekshith142 — APPROVED** [review]
Everything is good with the Aboutdesign and sign-in pages

**Comment by briangormanly** [comment]
do not merge this!

**Comment by briangormanly** [comment]
I must approve all merges to main

**Comment by briangormanly** [comment]
I will review this when I have time, as I told the team that worked on it would not likely be before the presentation on Monday

**Comment by Murali2255** [comment]
> I will review this when I have time, as I told the team that worked on it would not likely be before the presentation on Monday

Sure, Professor. We won't merge this.

**Comment by briangormanly** [comment]
Archiving

**Pull request closed without merging**
