### PR TITLE
Adding interface for discussions and some DOM manipulation for it

### PR DESCRIPTION
**Pull request by MaxEnglish**
-discussions modal on topic page
-"like" dom manipulation
-adding new comment dom manipulation

image

### CODE REVIEW

**Review by KyleRessLiere — APPROVED** [review]
Looking good

**Review by briangormanly — CHANGES_REQUESTED** [review]
It looks good, just pull main to resolve the conflict first.

**Comment by MaxEnglish** [comment]
Merged with main

**Review by briangormanly — APPROVED** [review]
good to go.

**Pull request merged**
