### PR TITLE
Homepage fix (doesn't break dashboard anymore)

### PR DESCRIPTION
**Pull request by RichieConsiglio**
Found out that the other homepage was built off my right click sub menu branch, which is why the dashboard was broken. Moved home redo to a recently pulled main so it wouldn't be far behind in the merge.

### CODE REVIEW

**Comment by briangormanly** [comment]
Is this a replacement for #211 ? If so go ahead and close that one, but in the future it is better to keep all the history in one place.

**Comment by KyleRessLiere** [comment]
On my default screen size the sign in option and profile are not showing. Available when zooming out.
image

When zoomed out I can see it at 80%
image

My mac screen size is 13""

**Comment by RichieConsiglio** [comment]
> On my default screen size the sign in option and profile are not showing. Available when zooming out. image
> 
> When zoomed out I can see it at 80% image
> 
> My mac screen size is 13""

Just pushed a fix for this, let me know if it displays properly!

**Review by KyleRessLiere — APPROVED** [review]
Merged with main. looking good

**Review by sbrad93 — APPROVED** [review]
Looks great

**Review by briangormanly — APPROVED** [review]
Good to go.

**Pull request merged**
