### PR TITLE
Print uncaught error to console and fix discussion enabling

### PR DESCRIPTION
**Pull request by kiikoh**
With PR #237 errors stopped being printed to console making development hard. 

Also, we found a bug in the creation of discussions

### CODE REVIEW

**Review by cmarcusdimarco — COMMENTED** [review]
Waiting to approve until the renaming of goals to workspaces takes place. I suspect a merge conflict will be coming. Looks good other than that.

**Comment by kiikoh** [comment]
Ok just wanna make sure people see when they get an error... also doubt this will cause any conflict

**Review by briangormanly — APPROVED** [review]
This one does not look like it has any conflicts, good to go.

**Comment by briangormanly** [comment]
Since it was only waiting on conflicts I will override the merge

**Pull request merged**
