### PR TITLE
Topic enhancements

### PR DESCRIPTION
**Pull request by sbrad93**
- Created topic title, updates topic tab name
- Topic POST request
- Styling updates to workspace header

### CODE REVIEW

**Comment by briangormanly** [comment]
Make sure to pull main to resolve the conflicts.

**Review by briangormanly — APPROVED** [review]
I played around a bit and got it to save topics (but it showed them as 'untitled') getting closer!

**Comment by briangormanly** [comment]
@KyleRess-Liere let me know if you are okay with this one so we can merge it.

**Review by KyleRessLiere — APPROVED** [review]
Look good

**Pull request merged**
