### PR TITLE
Middleware Features: better auth, input validation, and error handling

### PR DESCRIPTION
**Pull request by kiikoh**
This PR introduces a handful of helpful utilities to make development faster and more standardized across teams. All features are opt-in but highly encouraged. So far the discussion API stack is the only set of APIs using these middleware but if applied to all, could greatly increase code readability, reliability, and user experience. 

One area I am uncertain of is the file structure

I see a few issues with the way it is done now, but I can't come up with a way that feels "correct" enough to bother changing it

### CODE REVIEW

**Comment by kiikoh** [comment]
@Tones55 @Christopher102 were involved in the development of the code in this PR

**Review by briangormanly — COMMENTED** [review]
Going to pull this and play around with it, before merging. Looks good.

**Review by cmarcusdimarco — APPROVED** [review]
Approving for @briangormanly to merge when ready. I think this looks fantastic - great work from all engineers involved.

**Comment by kiikoh** [comment]
Another thing I wanted to mention was the originally planned way of throwing errors which will get caught cannot be implemented. Express 5 which is somehow still in beta would enable this, or package to add this feature in as described in this article https://medium.com/@utkuu/error-handling-in-express-js-and-express-async-errors-package-639c91ba3aa2

**Review by briangormanly — APPROVED** [review]
This is really good, looking forward to seeing it implemented in more apis

**Pull request merged**
