### PR TITLE
Richie home redo

### PR DESCRIPTION
**Pull request by RichieConsiglio**
Redo of index page that I presented in class last week. 
Took some time this week to fix formatting/zoom problems before submitting PR.

Changes only effect index/home page.

### CODE REVIEW

**Review by briangormanly — APPROVED** [review]
Good start.

**Comment by KyleRessLiere** [comment]
Currently breaks the dashboard. No items are showing

**Comment by briangormanly** [comment]
@KyleRessLiere is correct (good catch), I did not go past the homepage trying to get these in quickly for the Lint update, I am pulling my approval, but am not sure we should close the PR? 

If there is a quick fix that can be implemented to add this to main today re-submit for approval. Please make sure it is not breaking other parts of the UI

**Review by briangormanly — CHANGES_REQUESTED** [review]
Need to fix Dashboard, currently breaks.

**Comment by KyleRessLiere** [comment]
Yeah no problem richie said he gonna look into it. I just stopped because I wasnt the reviewer and wanted to make sure it didnt fall onto main

**Pull request closed without merging**
