### PR TITLE
update fields on topic page from backend and small dashboard changes

### PR DESCRIPTION
**Pull request by MaxEnglish**
-Name and description update on topic page from backend
-Fixed url updating when entering a topic/goal from the dashboard
-Added trimming to dashboard names and descriptions
-changed copy link button in more options menu to copy the correct link
-duplicating a card will add it the beginning of the lists of goals or topics instead of the end (DOM only)
-ids being assigned to cards will occur based on backend response data before page refresh

### CODE REVIEW

**Comment by MaxEnglish** [comment]
This pr overlaps with my pr from yesterday. I will close it but it has the details of that pr in the description so I will wait.

**Comment by KyleRessLiere** [comment]
Repeated function newTabCards

**Review by KyleRessLiere — APPROVED** [review]
Looking good. Es-lint and repeated function resolved

**Comment by briangormanly** [comment]
Please make sure all List checks are successful! (currently failing)

**Comment by KyleRessLiere** [comment]
@briangormanly Everything should be good to go. We had to update id's for the backend changes that just came in. Additionally we are now passing all linter checks

**Review by briangormanly — APPROVED** [review]
approved.

**Pull request merged**
