### PR TITLE
198 goal to workspace

### PR DESCRIPTION
**Pull request by JamesVetro**
New pull request for changing goal to workspace, incorporating the updated agora setup.

### CODE REVIEW

**Comment by briangormanly** [comment]
there are some conflicts with main, trying pulling main into this branch to resolve them in the branch.

**Review by cmarcusdimarco — COMMENTED** [review]
@Mike-Volchko I know @JamesVetro and @AntL552 have been working on this for a couple weeks now and likely have been struggling to balance it with getting Cyber up and running. You and I should tackle this Wednesday night if James and Antonio need a hand.

**Comment by Mike-Volchko** [comment]
@cmarcusdimarco  Sounds like a plan.

**Comment by JamesVetro** [comment]
This pull request was updated to the second version.

**Comment by JamesVetro** [comment]
Incorrect duplicate closed
My bad

**Review by cmarcusdimarco — CHANGES_REQUESTED** [review]
Testing after the work day with @Mike-Volchko reveals that changes will need to be made - specifics to follow after he and I meet Thursday morning.

**Comment by Mike-Volchko** [comment]
After pulling down the changes and testing there seems to be some bugs. @cmarcusdimarco and I will debug tomorrow morning and try to solve the issues.

**Review by cmarcusdimarco — APPROVED** [review]
Alongside @Mike-Volchko - reverted database query statements and env variables. Refactored remaining files. Reuploaded peak.svg.

All devs will need to change their .env files on lines 20 and 26 to use path /assets/uploads/workspace instead of /assets/uploads/goals.

Tested successfully by @Mike-Volchko and I.

**Review by Mike-Volchko — APPROVED** [review]

**Comment by cmarcusdimarco** [comment]
@briangormanly we are ready on this PR when you are. If possible for you to review ASAP, it would be a huge help - there is an active PR that is blocking front-end and we are waiting on this to go to main to push through the merge conflicts it will introduce.

**Review by briangormanly — APPROVED** [review]
Sorry for the delay, good to go!

**Pull request merged**
